# Generated by Django 3.1.7 on 2021-05-09 11:56

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/default.png', upload_to=blog_app.models.rename('profile_pictures')),
        ),
    ]
