# Generated by Django 4.0.1 on 2022-01-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_blog_user_liked_alter_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='likes',
            new_name='likes_count',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_liked',
            new_name='user_likes',
        ),
    ]
